using Code.Dialogue.Helpers;
using Ink.Runtime;
using UnityEngine;

namespace Code.Dialogue
{
    public class Speaker : MonoBehaviour // TODO: ScriptableObject instead
    {
        [Tooltip("The .json file, generated by Ink, containing the dialogue")]
        public TextAsset inkFile;

        [Range(0.85f, 1f, order = 100)] [Tooltip("How fast the text is displayed")]
        public float speed = 0.95f;

        public DialogueBox dialogueBox;
        public Story story;

        private GameObject _textBox;
        // private bool _isTalking = false; // For SpeakerAnimation

        public void Start()
        {
            _textBox = transform.Find("TextBox").gameObject;
            dialogueBox = new DialogueBox(_textBox, name, speed);
            _textBox.SetActive(false);
            story = new Story(inkFile.text);
            story.BindExternalFunction("color", (string text, string theme) => DialogueCallbacks.Color(text, theme), true);
        }

        public void OnClick()
        {
            StartConversation();
        }

        private void StartConversation()
        {

            if (DialogueManager.SetSpeaker(this))
            {
                _textBox.SetActive(true);
				string nextDialogue = story.variablesState[$"{name}_NextDialogue"].ToString();
                story.ChoosePathString(nextDialogue);
                Debug.Log("Story: " + story.currentText);
            }
            else
                Debug.Log("Speaker already set");
        }

        public void FinishConversation()
        {
            _textBox.SetActive(false);
        }
    }
}